### PR TITLE
port to python 38

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545

### CODE REVIEW

**Comment by harshad16** [comment]
Please change this image https://github.com/thoth-station/amun-api/blob/f15da5185e9709287cf3b3cad08a2aca4e501a3b/.aicoe-ci.yaml#L5 to `quay.io/thoth-station/s2i-thoth-ubi8-py38:latest`

**Comment by bissenbay** [comment]
> Please change this image
> 
> https://github.com/thoth-station/amun-api/blob/f15da5185e9709287cf3b3cad08a2aca4e501a3b/.aicoe-ci.yaml#L5
> 
> to `quay.io/thoth-station/s2i-thoth-ubi8-py38:latest`
> this would fix the build issues and we would also get know if that if the image would work.

thanks a lot, @harshad16

**Review by fridex — APPROVED** [review]
:100:

**Pull request merged**
