### PR TITLE
Allow maintainers to release the application

### PR DESCRIPTION
**Pull request by harshad16**
Allow maintainers to release the application
Related-to: #446 
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Comment by goern** [comment]
this is the most approved PR :) EVVA!!!

**Comment by goern** [comment]
its just waiting for some chekcs to be :green_heart: https://github.com/thoth-station/test-infra/blob/master/thoth-station/config.yaml#L130-L134

**Comment by harshad16** [comment]
> /retest

this will have no effect as pre-commit needs to exists here. 
which will happen once this is merged: https://github.com/thoth-station/amun-api/pull/449

**Comment by harshad16** [comment]
The merging with tide needs to be investigated 
as based on this https://prow.thoth-station.dev/pr?query=is%3Apr%20repo%3Athoth-station%2Famun-api%20author%3Aharshad16%20head%3Amaintain
this should be merged.

**Pull request merged**
