### PR TITLE
add openshift schedule params for inspection complete message

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

Depends on: https://github.com/thoth-station/common/pull/1107

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

I added args so that message contents and behaviour can be adjusted

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
lgtm :+1:

**Comment by KPostOffice** [comment]
@fridex New params do not need to be added to `openshift.schedule_inspection`.  All params can be parsed from `specification`

**Comment by fridex** [comment]
> @fridex New params do not need to be added to `openshift.schedule_inspection`. All params can be parsed from `specification`

Sounds good. :+1: I think we can close https://github.com/thoth-station/common/pull/1107 this way.

**Comment by KPostOffice** [comment]
> > @fridex New params do not need to be added to `openshift.schedule_inspection`. All params can be parsed from `specification`
> 
> Sounds good. +1 I think we can close [thoth-station/common#1107](https://github.com/thoth-station/common/pull/1107) this way.

Yeah, I adjusted that PR so that it gets the new template params from `specification`

**Comment by KPostOffice** [comment]
@fridex is this GTG

**Review by fridex — APPROVED** [review]
lgtm, thanks! :+1:

**Pull request merged**
