### PR TITLE
Adjust inspections to use argo for running inspections

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
I think I hit https://github.com/argoproj/argo/issues/1868 - the inspection builds and runs correctly finish but at the end, the parallel part of the workflow fails on `template create-job not found`.

**Comment by harshad16** [comment]
recheck

**Comment by fridex** [comment]
And resource requests fail to validate due to https://github.com/argoproj/argo/issues/2412

**Comment by fridex** [comment]
Discarding WIP flag, ready for a review.

**Comment by fridex** [comment]
recheck

**Pull request merged**
