### PR TITLE
Added different function for \n

### LINKED ISSUE #127: Correctly handle \n when writing file
We should correctly handle '\n' when writing data into file. When a performance script has "\n" in it for example:

```python
print("Hello, Thoth\n")
```

The file placed into container image is:

```python
print("Hello, Thoth
")
```

Which causes syntax errors. We should correctly escape it (see dockerfile.py file).

### PR DESCRIPTION
**Pull request by saisankargochhayat**
Closes #127 
Sample docker file generated - https://paste.ofcode.org/33QsfYngtMiKcRCmA3Rn7MH
So using removing the extra `\\n`, was leading to fail for entrypoint, so I moved it to a different function and changed the `_write_file_string`. 
Ref - http://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html
Is this the right way to do it?

### CODE REVIEW

**Comment by fridex** [comment]
> So using removing the extra `\\n`, was leading to fail for entrypoint, so I moved it to a different function and changed the `_write_file_string`.

I think I'm missing why is that - why entry point needs to be treated in a different way?

**Comment by saisankargochhayat** [comment]
> > So using removing the extra `\\n`, was leading to fail for entrypoint, so I moved it to a different function and changed the `_write_file_string`.
> 
> I think I'm missing why is that - why entry point needs to be treated in a different way?

I am not sure why, but the dockerfile generated using without the extra \n seems to fail on dockerbuild

**Comment by fridex** [comment]
> > > So using removing the extra `\\n`, was leading to fail for entrypoint, so I moved it to a different function and changed the `_write_file_string`.
> > 
> > 
> > I think I'm missing why is that - why entry point needs to be treated in a different way?
> 
> I am not sure why, but the dockerfile generated using without the extra \n seems to fail on dockerbuild

Hm.. I cannot think why this issue occurs. Could you try to test it also with Python packages? In that case, Pipfile and Pipfile.lock should be written using the same function.

**Comment by saisankargochhayat** [comment]
> > > > So using removing the extra `\\n`, was leading to fail for entrypoint, so I moved it to a different function and changed the `_write_file_string`.
> > > 
> > > 
> > > I think I'm missing why is that - why entry point needs to be treated in a different way?
> > 
> > 
> > I am not sure why, but the dockerfile generated using without the extra \n seems to fail on dockerbuild
> 
> Hm.. I cannot think why this issue occurs. Could you try to test it also with Python packages? In that case, Pipfile and Pipfile.lock should be written using the same function.

https://paste.ofcode.org/35ygjXsAaJUkZPmXhqCk7Rw
Here the generated dockerfile and the error without the extra \n, I am going to try with Pipfile and Pipfile.lock now.

**Comment by saisankargochhayat** [comment]
As the Pipfile and Pipfile.lock, aren't working, I am reverting to the older function, and only writing the script uses new write to file function.

**Comment by saisankargochhayat** [comment]
@fridex Does this need any changes? :)

**Comment by fridex** [comment]
> @fridex Does this need any changes? :)

I'm not sure why there is needed a new function for this. Will this fix \n also for Pipfile/Pipfile.lock written?

**Comment by saisankargochhayat** [comment]
The script used to test get the dockerfile generated. 
https://paste.ofcode.org/mt5JMUE9ie3sjLMU2JhFk2

**Pull request merged**
