### PR TITLE
Adjust logic for optaining CPU related statistics of the child process

### PR DESCRIPTION
**Pull request by fridex**
Fixes: https://github.com/thoth-station/amun-api/issues/199

### CODE REVIEW

**Comment by fridex** [comment]
Example:

```
$ oc logs -f -n thoth-test-core inspection-58cbd0d67cee938b-kb8m2
{
  "cpu": {
    "ru_idrss": 0,
    "ru_inblock": 96,
    "ru_isrss": 0,
    "ru_ixrss": 0,
    "ru_majflt": 1,
    "ru_maxrss": 141504,
    "ru_minflt": 71922,
    "ru_msgrcv": 0,
    "ru_msgsnd": 0,
    "ru_nivcsw": 87647261,
    "ru_nsignals": 0,
    "ru_nswap": 0,
    "ru_nvcsw": 972478,
    "ru_oublock": 24,
    "ru_stime": 203.760891,
    "ru_utime": 383.174859
  },
  "datetime": "2019-07-18T20:46:22.921698",
  "exit_code": null,
...
```

**Comment by fridex** [comment]
Not sure if that matches elapsed though...

**Comment by fridex** [comment]
> Not sure if that matches elapsed though...

Hm... It can be related to CPU assigned for the container.

**Comment by pacospace** [comment]
> Not sure if that matches elapsed though...

What do you mean?

**Comment by fridex** [comment]
> > Not sure if that matches elapsed though...
> 
> What do you mean?

The sum of time spent in user space and kernel space is higher than time reported in `elapsed`. It's due to number of allocated CPUs on machine in the cluster.

**Pull request merged**
